name: Colin Davis
favicon: null
layout_spectrum: 0.7396277533844113
typography_spectrum: 0.6800392519216985
title: Studio Colin Davis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#daefe2'
    - '#08130f'
    - '#738996'
    - '#a94757'
    - '#fc7765'
  brandStrength: 0.2967808358371258
  lightness: 0.917527154320851
  saturation: 0.75
  rhythmicContrast: 0.6591691332869232
purpose: []
